###### ###### ###### ###### ###### ###### ###### 
###### Packages                           ###### 
###### ###### ###### ###### ###### ###### ###### 

load_packages <- function(updateR){

  
if (updateR==TRUE){
  #install.packages("installr")
  library(installr)
  updateR()
}
  
packages <- c("tidyverse","tidymodels","dplyr", "pdp",
             "CASdatasets","iml","gbm", "testit", "flashlight",
             "ggpmisc", "dbplyr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())

if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages], dependencies = TRUE)
}

# Loading packages not yet loaded
loaded_packages <- packages %in% (.packages())

if (any(loaded_packages == FALSE)) {
  lapply(packages[!loaded_packages], require, character.only = TRUE)
}

       
       
}

## SAVE Mathias paket

# packages <- c("Rtools","abind",
#               "actuar",
#               "ash",
#               "askpass",
#               "assertthat",
#               "backports",
#               "base",
#               "base64enc",
#               "BH",
#               "biglm",
#               "bitops",
#               "boot",
#               "brew",
#               "broom",
#               "callr",
#               "car",
#               "carData",
#               "cellranger",
#               "ChainLadder",
#               "class",
#               "cli",
#               "clipr",
#               "clisymbols",
#               "cluster",
#               "cobs",
#               "coda",
#               "codetools",
#               "colorspace",
#               "commonmark",
#               "compiler",
#               "config",
#               "covr",
#               "cplm",
#               "crayon",
#               "crosstalk",
#               "curl",
#               "data.table",
#               "datasets",
#               "DBI",
#               "dbplyr",
#               "demography",
#               "desc",
#               "devtools",
#               "digest",
#               "dlm",
#               "doParallel",
#               "dotCall64",
#               "dplyr",
#               "DT",
#               "ellipsis",
#               "evaluate",
#               "expint",
#               "fanplot",
#               "fansi",
#               "farver",
#               "fastmap",
#               "fda",
#               "fields",
#               "FNN",
#               "forcats",
#               "foreach",
#               "forecast",
#               "foreign",
#               "fracdiff",
#               "fs",
#               "ftsa",
#               "gbm",
#               "generics",
#               "geometry",
#               "ggplot2",
#               "ggthemes",
#               "gh",
#               "git2r",
#               "glue",
#               "gnm",
#               "graphics",
#               "grDevices",
#               "grid",
#               "gridExtra",
#               "gtable",
#               "haven",
#               "hdrcde",
#               "highr",
#               "hms",
#               "htmltools",
#               "htmlwidgets",
#               "httpuv",
#               "httr",
#               "ini",
#               "isoband",
#               "iterators",
#               "jsonlite",
#               "keras",
#               "kernlab",
#               "KernSmooth",
#               "knitr",
#               "ks",
#               "labeling",
#               "later",
#               "lattice",
#               "lazyeval",
#               "lifecycle",
#               "linprog",
#               "lme4",
#               "lmtest",
#               "locfit",
#               "lpSolve",
#               "lubridate",
#               "magic",
#               "magrittr",
#               "maps",
#               "maptools",
#               "markdown",
#               "MASS",
#               "Matrix",
#               "MatrixModels",
#               "mclust",
#               "memoise",
#               "methods",
#               "mgcv",
#               "mime",
#               "minqa",
#               "modelr",
#               "multicool",
#               "munsell",
#               "mvnfast",
#               "mvtnorm",
#               "nlme",
#               "nloptr",
#               "nnet",
#               "numDeriv",
#               "openssl",
#               "openxlsx",
#               "parallel",
#               "pbkrtest",
#               "pcaPP",
#               "pdfCluster",
#               "pillar",
#               "pkgbuild",
#               "pkgconfig",
#               "pkgload",
#               "plogr",
#               "plyr",
#               "praise",
#               "prettyunits",
#               "processx",
#               "progress",
#               "promises",
#               "ps",
#               "purrr",
#               "quadprog",
#               "quantmod",
#               "quantreg",
#               "qvcalc",
#               "R6",
#               "rainbow",
#               "rappdirs",
#               "rcmdcheck",
#               "RColorBrewer",
#               "Rcpp",
#               "RcppArmadillo",
#               "RcppEigen",
#               "RcppProgress",
#               "RCurl",
#               "readr",
#               "readxl",
#               "relimp",
#               "rematch",
#               "remotes",
#               "reprex",
#               "reshape",
#               "reshape2",
#               "reticulate",
#               "rex",
#               "rio",
#               "rlang",
#               "rmarkdown",
#               "rootSolve",
#               "roxygen2",
#               "rpart",
#               "rprojroot",
#               "rstudioapi",
#               "rversions",
#               "rvest",
#               "sandwich",
#               "scales",
#               "sde",
#               "selectr",
#               "sessioninfo",
#               "shiny",
#               "sourcetools",
#               "sp",
#               "spam",
#               "SparseM",
#               "spatial",
#               "splines",
#               "statmod",
#               "stats",
#               "stats4",
#               "StMoMo",
#               "stringi",
#               "stringr",
#               "strucchange",
#               "survival",
#               "sys",
#               "systemfit",
#               "tcltk",
#               "tensorflow",
#               "testthat",
#               "tfruns",
#               "tibble",
#               "tidyr",
#               "tidyselect",
#               "tidyverse",
#               "timeDate",
#               "tinytex",
#               "tools",
#               "tseries",
#               "TTR",
#               "tweedie",
#               "urca",
#               "usethis",
#               "utf8",
#               "utils",
#               "vctrs",
#               "viridisLite",
#               "whisker",
#               "withr",
#               "xfun",
#               "xml2",
#               "xopen",
#               "xtable",
#               "xts",
#               "yaml",
#               "zeallot",
#               "zip",
#               "zoo"
# )
